#user spring config
debug: true
server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: newcatering
    url: jdbc:mariadb://54.180.107.191:3305/trip


custom:
  jwt:
    secret: TestKey
    expiration: 604800000
    header: Authorization
